name: Deploy Back-end

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14

    - name: Log in to Heroku Registry
      run: heroku container:login
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

    - name: Generate Prisma Client
      run: npx prisma generate   
      
    - name: Build and Push Docker Image
      run: |
        heroku container:push -a candidate-test-backend web
        heroku container:release -a candidate-test-backend web
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
